In [1]:
import tensorflow as tf
import tensorflow_hub as hub

Tensorflow-hub 是 google 提供的机器学习模组打包函式库，帮开发者把TensorFlow的训练模型发布成模组，方便再次使用或是与社交共享。  
打包用来发布机器学习中可重复使用的部分，包括TensorFlow_Graph、权重以及外部档案等所需资源。  
这些模组包含了大量资料集预训练后取得的变量，可以供类似任务使用。  
这样的成果可以使后续开发者，用更少的资料集训练精准模型、改进泛化或是大幅提升模型训练速


In [2]:
print(tf.__version__)
print("Eager mode: ",tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.test.is_gpu_available() else "NOT AVAILABLE")

2.0.0-rc2
Eager mode:  True
Hub version:  0.6.0
GPU is NOT AVAILABLE


In [3]:
from __future__ import absolute_import, division, print_function

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass


# NumPy兼容性
在TensorFlow tf.Tensors和NumPy ndarray之间进行转换很容易：  
- TensorFlow操作会自动将NumPy ndarray转换为Tensors。  
- NumPy操作会自动将张量转换为NumPy ndarray  

In [7]:
import numpy as np

ndarray = np.ones([3, 3])
print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)

print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

narray=np.asarray([[1,2,3],[4,5,6]],dtype=np.int32)
tensor1 = tf.convert_to_tensor(narray)
print(tensor1)

with tf.I as sess:
    print(tensor1.eval(sess))

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


AttributeError: module 'tensorflow' has no attribute 'Session'

In [8]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available: "),
print(tf.config.experimental.list_physical_devices("GPU"))

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))


Is there a GPU available: 


(None,)

[]
Is the Tensor on GPU #0:  


(None,)

False
